version: "3.3"
services:
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"
  db:
    image: "mysql:8.0.18"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moyu

    volumes:
      - type: bind
        source: ./scripts/sql/database.sql
        target: /docker-entrypoint-initdb.d/database.sql

    ports:
      - "3306:3306"