### 1.8.1 分页读取通知
GET {{host}}/api/notices?size=1000&page=1
Cookie: {{cookie}}
Content-Type: application/json;charset=utf8
X-Csrf-Token: {{csrf}}

### 1.8.2 批量已读
POST {{host}}/api/notices/read
Cookie: {{cookie}}
Content-Type: application/json;charset=utf8
X-Csrf-Token: {{csrf}}

{
  "ids": [5]
}
### 读取未读消息数
GET {{host}}/api/notices/unread-count
Cookie: {{cookie}}
Content-Type: application/json;charset=utf8
X-Csrf-Token: {{csrf}}