apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: __APP_NAME__
  namespace: __NS__
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: __APP_NAME__
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90