// Code generated by MockGen. DO NOT EDIT.
// Source: i_persistence.go

// Package stat is a generated GoMock package.
package stat

import (
	goneMock "github.com/gone-io/gone"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockiPersistence is a mock of iPersistence interface.
type MockiPersistence struct {
	goneMock.Flag
	ctrl     *gomock.Controller
	recorder *MockiPersistenceMockRecorder
}

// MockiPersistenceMockRecorder is the mock recorder for MockiPersistence.
type MockiPersistenceMockRecorder struct {
	mock *MockiPersistence
}

// NewMockiPersistence creates a new mock instance.
func NewMockiPersistence(ctrl *gomock.Controller) *MockiPersistence {
	mock := &MockiPersistence{ctrl: ctrl}
	mock.recorder = &MockiPersistenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockiPersistence) EXPECT() *MockiPersistenceMockRecorder {
	return m.recorder
}

// listTopReplyMsg mocks base method.
func (m *MockiPersistence) listTopReplyMsg(top int, channelId int64) ([]*hotMsg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "listTopReplyMsg", top, channelId)
	ret0, _ := ret[0].([]*hotMsg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// listTopReplyMsg indicates an expected call of listTopReplyMsg.
func (mr *MockiPersistenceMockRecorder) listTopReplyMsg(top, channelId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "listTopReplyMsg", reflect.TypeOf((*MockiPersistence)(nil).listTopReplyMsg), top, channelId)
}
